# syntax=docker/dockerfile:1
FROM golang:1.26.1 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY cmd ./cmd
COPY pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/app ./cmd/seed

#Run
FROM alpine:latest

WORKDIR /root

COPY --from=builder /app/app .
COPY seed/img ./seed/img

CMD [ "./app" ]
