services:
  # ============= DATABASES =============
  postgres-interaction:
    image: postgres:18
    container_name: postgres_interaction
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - pgdata-interaction:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8.8-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD:-secret}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  # ============= MIGRATION SERVICES =============

  migrate-interaction:
    image: migrate/migrate
    env_file: .env.dev
    volumes:
     - ./migrations:/migrations
    command: -path /migrations -database  postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-interaction:5432/${POSTGRES_DB}?sslmode=disable up
    depends_on:
      postgres-interaction:
        condition: service_healthy
    restart: no

# ============= VOLUMES =============

volumes:
  pgdata-interaction:
  redis_data:
